Revert "upgrade docker-ngts to 1.2.464"
This reverts commit e36231857a254c7fecabd49cae578da2b6ff5af7.

Reason for revert: Might lead to AttributeError: module 'ansible.plugins.action.shell' has no attribute 'ActionModule'

Change-Id: I0c7d4a6aa8731d8e1c2b8a53f5ffb2b343952bd0