T2:Snappi Tests:Cisco-8000:Remove la_error ignore fixture, and fix the occurance of LA errors. (#17934)
Description of PR
Summary:
Recently #17012 introduced static routes-based destinations for snappi tests. That PR included a LA-error ignore fixture, since the static route introduced two LA errors during the runs. This PR removes this fixture, and updates the static route functions to completely remove the LA Error in the first place. The LA errors were:

routeCheck' status failed .*", r".*missing interface entry for static route.
RouteCheck error disappeared after making sure the static route's outgoing interface always has an IP address. So, we should always add route after IP address, and remove the route before the IP address.
The second "missing interface" error is from arp_update. This disappeared after making sure there is an arp entry for the GW address used by the static route. When this arp entry is missing, we see that error.
Type of change
 Bug fix
 Testbed and Framework(new/improvement)
 Test case(new/improvement)
Back port request
 201911
 202012
 202205
 202305
 202311
 202411
 202405
Approach
What is the motivation for this PR?
Pls see the description.

How did you do it?
As mentioned in description.

How did you verify/test it?
Ran it on T2 TB:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================================================================== PASSES ===========================================================================================================================
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config0] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config1] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config2] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config3] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config0] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config1] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config2] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config3] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config1] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config2] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config3] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config0] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config1] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config2] _______________________________________________________________________________________
______________________________________________________________________________________ test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config3] _______________________________________________________________________________________
-------------------------------------------------------------------------------------- generated xml file: /run_logs/100G/ecn-la-error-test/2025-04-08-20-11-47/tr.xml ---------------------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
================================================================================================================== short test summary info ===================================================================================================================
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config0]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config1]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config2]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info0-test_ecn_config3]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config0]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config1]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config2]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info1-test_ecn_config3]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config1]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config2]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config3]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config0]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config1]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config2]
PASSED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config3]
ERROR snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info3-test_ecn_config3] - Failed: Not all bgp sessions are established after config reload
FAILED snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py::test_ecn_marking_with_pfc_quanta_variance[multidut_port_info2-test_ecn_config0] - snappi_ixnetwork.exceptions.SnappiIxnException:   File "/usr/local/lib/python3.8/dist-packages/snappi_ixnetwork/snappi_api.py", line 502, in get_metrics
============================================================================================== 1 failed, 15 passed, 20 warnings, 1 error in 18529.96s (5:08:49) ==============================================================================================
sonic@snappi-sonic-mgmt-msft-t2:/data/tests$
sonic@snappi-sonic-mgmt-msft-t2:/data/tests$
sonic@snappi-sonic-mgmt-msft-t2:/data/tests$
Any platform specific information?
Cisco-8000 only.

co-authorized by: jianquanye@microsoft.com

Change-Id: I1cb4addeccc19d526de36cc65c50fde4f9ae459d