Fix `test_lo_interface.py` on t2/voq systems (#23589)
### Description of PR
T2/VOQ systems have a Loopback4096 interface which returns an error when
`generic_config_updater/test_lo_interface.py` tries to delete it.
```
> sudo config loopback del Loopback4096
Usage: config loopback del [OPTIONS] <loopback_name>
Try 'config loopback del -h' for help.

Error: Loopback4096 is invalid, name should have prefix 'Loopback' and suffix '<0-999>'
```

The test doesn't need to delete this interface so skip it.
More details in https://github.com/sonic-net/sonic-mgmt/issues/23586

Summary:
Fixes #23586

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [x] 202511

### Approach
#### What is the motivation for this PR?
Fix `generic_config_updater/test_lo_interface.py` on T2/VOQ systems

#### How did you do it?
Don't delete Loopback4096

#### How did you verify/test it?
Ran `generic_config_updater/test_lo_interface.py` on a T2/VOQ system and
saw it passed

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?
N/A

### Documentation
N/A

Change-Id: I7223fe63cafbde1e3dbfb426d09492f297edb01f
Signed-off-by: Nathan Wolfe <nwolfe@arista.com>